name: feature_discovery_badges
description: Demo of a simple feature discovery with badges

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
