name: feature_discovery_badges
description: Demo of a simple feature discovery with badges

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
