enum FeatureId {
  home,
  news,
  newsDetail,
  newsDetailShare,
  newsDetailBookmark,
  newsDetailComment,
  profile,
  profileEmail,
  profilePassword,
  settings,
  settingsNotifications,
  settingsNotificationsPush,
  settingsNotificationsSms,
  settingsAppearance,
  settingsAppearanceDarkMode,
  settingsAppearanceLanguage,
}
